apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
  labels:
    app: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-image-updater
        image: vamsi011/django-app:v1.0.22
        ports:
        - containerPort: 8000
