apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
  labels:
    app: argocd
  annotations:
     # Assign alias 'chai-app' to your image
    argocd-image-updater.argoproj.io/image-list: chai-app=vamsi011/django-app # Maps the image alias 'chai-app' to your DockerHub image

    # Use git write-back
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-image-updater-git-creds # Configures image updater to write changes back to Git using provided secret

    # Update strategy for chai-app image
    argocd-image-updater.argoproj.io/chai-app.update-strategy: semver # Uses semantic versioning for image updates

spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - name: argocd-image-updater
        image: vamsi011/django-app:v1.0.22
        ports:
        - containerPort: 8000
