apiVersion: v1 # Specifies the API version for Kubernetes resources
kind: Secret # Declares that this resource is a Secret
metadata:
  name: argocd-image-updater-git-creds # Name of the Secret object
  namespace: argocd # Namespace where the Secret will be created
stringData:
  username: vamshireddy903 # Your GitHub username for authentication
  password: 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    # Your GitHub personal access token for authentication
