# chai-app.yaml
# This file defines an ArgoCD Application resource for deploying the chai-app.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chai-app # Name of the ArgoCD application
  namespace: argocd # Namespace where ArgoCD is installed
  annotations:
    # The email notifier must be configured in argocd-notifications-cm.yaml, The `.email` is the name of the notifier, i.e, `service.email` in the argocd-notifications-cm.yaml.
    # Subscribe to notifications when the app health is degraded.
    notifications.argoproj.io/subscribe.on-health-degraded.email: "<receiver@example.com>"  # you can add multiple email ids separated by comma like "<receiver@example.com>, <receiver2@example.com>"
    # Subscribe to notifications when the app is successfully deployed.
    notifications.argoproj.io/subscribe.on-deployed.email: "<receiver@example.com>" # you can add multiple email ids separated by comma like "<receiver@example.com>, <receiver2@example.com>"
spec:
  project: default # ArgoCD project this app belongs to
  source:
    repoURL: https://github.com/<your-username>/argocd-demos.git # Git repository containing the app manifests
    targetRevision: main # Git branch, tag, or commit to track
    path: applicationsets/chai-app # Path within the repo where manifests are located
  destination:
    server: https://kubernetes.default.svc # Kubernetes API server address (in-cluster)
    namespace: default # Namespace where the app will be deployed
  syncPolicy:
    automated:
      prune: true # Automatically delete resources that are no longer defined in Git
      selfHeal: true # Automatically correct drift between Git and cluster state

# Brief Info:
# This manifest enables GitOps for chai-app using ArgoCD.
# Notifications are set up for health degradation and deployment events.
# Automated sync ensures the cluster matches the desired state in Git.